#Specify the bae image
FROM node:16-alpine

WORKDIR '/app'
 
#COPY package.json file to the container
COPY ./package.json ./

#Install Some Dependencies
RUN npm install

COPY ./ ./

#Default Command
CMD ["npm","run","start"]